project:
  type: website

website:
  search: false
  navbar:
    logo: "assets/logo.png"
    right:
      - href: index.qmd
        text: Home
      - href: "#programs-section"
        text: Programs
      - href: "#events-section"
        text: Events
      - href: donate.qmd
        text: Donate
      - href: about.qmd
        text: About
      - href: contact_us.qmd
        text: Contact Us

format:
  html:
    theme: lux
    css: styles.css
    toc: false

editor: visual

