project:
  type: website
    
website:
  search: false
  repo-url: "https://github.com/esqLABS/cls-website"
  site-url: "https://clsfoundation.org/"
  favicon: "assets/CLSFoundation_LogoGraphics.png"
  draft-mode: gone
  navbar:
    logo: "assets/CLSFoundation_LogoGraphics.png"
    right:
      - text: Home 
        href: index.qmd
      - text: Programs
        href: programs.qmd
      - text: Events
        href: events.qmd
      - text: Stories
        href: stories.qmd
      - text: Donate
        href: donate.qmd
      - text: About
        href: about.qmd
      - text: Contact Us
        href: contact_us.qmd
  page-footer:
    left: |
      **Contact**
      
      CLS Foundation  
      Am Sportplatz 7  
      26683 Saterland  
      Germany  
      
      [+49 15158559070](tel:+4915158559070)  
      [info@clsfoundation.org](mailto:info@clsfoundation.org)


    center: |
      **Menu**
      
      [<i class="bi bi-house-door"></i> Home](/)  
      [<i class="bi bi-card-list"></i> Programs](/programs.html)  
      [<i class="bi bi-calendar-event"></i> Events](/events.html)  
      [<i class="bi bi-chat-quote"></i> Success Stories](/stories.html)  
      [<i class="bi bi-heart"></i> Donate](/donate.html)  
      [<i class="bi bi-info-circle"></i> About](/about.html)
      

    right: |
      **Links**
      
      [<i class="bi bi-file-text"></i> Imprint](/imprint)  
      [<i class="bi bi-shield-lock"></i> Data Privacy](/dataprivacy)
      
      **Connect**
      <div class="social-row">
        <a href="https://linkedin.com/company/clsfoundation/" class="social-icon" aria-label="LinkedIn"><i class="bi bi-linkedin"></i></a>
      </div>
      
      &copy; 2025 CLS Foundation
    background: light

format:
  html:
    theme: lux
    anchor-sections: false
    css: 
      - css/base.css
      - css/components.css
      - css/styles.css
      - css/footer.css
    toc: false
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    html-math-method: mathjax
    self-contained: false


