project:
  type: website

website:
  search: false
  navbar:
    logo: "https://esqlabs.com/wp-content/uploads/2018/05/ESQLABS_final_600px.png"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

editor: visual

