project:
  type: website

website:
  search: false
  favicon: "assets/CLSFoundation_LogoGraphics.png"
  navbar:
    logo: "assets/CLSFoundation_LogoGraphics.png"
    right:
      - href: index.qmd
        text: Home
      - href: "#programs-section"
        text: Programs
      - href: "#events-section"
        text: Events
      - href: donate.qmd
        text: Donate
      - href: about.qmd
        text: About
      - href: contact_us.qmd
        text: Contact Us

format:
  html:
    theme: lux
    css: styles.css
    toc: false
    include-after-body: "_includes/footer.html"


editor: visual

