project:
  type: website
    
website:
  search: false
  favicon: "assets/CLSFoundation_LogoGraphics.png"
  navbar:
    logo: "assets/CLSFoundation_LogoGraphics.png"
    right:
      - href: index.qmd
        text: Home
      - href: "#section-programs"
        text: Programs
      - href: "#section-events"
        text: Events
      - href: "#section-stories"
        text: Success Stories
      - href: "#section-donate"
        text: Donate
      - href: about.qmd
        text: About
      - href: contact_us.qmd
        text: Contact Us
  page-footer:
    left: |
      **Contact**
      
      CLS Foundation  
      Am Sportplatz 7  
      26683 Saterland  
      Germany  
      
      [+49 15158559070](tel:+4915158559070)  
      [info@clsfoundation.org](mailto:info@clsfoundation.org)

      ### 

    center: |
      **Menu**
      
      [<i class="bi bi-house-door"></i> Home](/)  
      [<i class="bi bi-card-list"></i> Programs](/#section-programs)  
      [<i class="bi bi-calendar-event"></i> Events](/#section-events)  
      [<i class="bi bi-chat-quote"></i> Success Stories](/#section-stories)  
      [<i class="bi bi-heart"></i> Donate](/donate)  
      [<i class="bi bi-info-circle"></i> About](/about)
      

    right: |
      **Links**
      
      [<i class="bi bi-file-text"></i> Imprint](/imprint)  
      [<i class="bi bi-shield-lock"></i> Data Privacy](/dataprivacy)
      
      **Connect**
      <div class="social-row">
        <a href="#" class="social-icon" aria-label="LinkedIn"><i class="bi bi-linkedin"></i></a>
      </div>
      
      &copy; 2024 CLS Foundation
    background: light

format:
  html:
    theme: lux
    anchor-sections: false
    css: 
      - css/base.css
      - css/components.css
      - css/layout.css
      - css/styles.css
      - css/footer.css
    toc: false
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    html-math-method: mathjax
    self-contained: false


