# Impressum

## LEGAL NOTICE
1. Information provided according to Sec. 5 German Telemedia Act (TMG)

Computational Life Sciences Foundation gUG
Am Sportplatz 7
26683 Saterland

2. Represented by
Dr. Stephan Schaller

3. Contact
Telephone: 0151/58559070
Email: info@clsfoundation.org

4. Register entry
Entry in the Handelsregister.
Registering court: Oldenburg
Registration number: HRB 212150

5. VAT
VAT Id number according to Sec. 27 a German Value Added Tax Act:
DE312671242

6. Webdesign and Webscripting:

ESQlabs GmbH
Am Sportplatz 7
26683 Saterland

7. Indication of source for images and graphics

Title graphic 3: www.open-systems-pharmacology.org
Titel graphic 2: AdobeStock © Gorodenkoff #166977042
Jobs graphic: AdobeStock © pressmaster #189825981

Remaining pictures from www.unsplash.com

8. Dispute resolution

The European Commission provides a platform for online dispute resolution (OS): https://ec.europa.eu/consumers/odr.

Please find our email in the Legal Notice.
We do not take part in online dispute resolutions at consumer arbitration boards.

## DISCLAIMER
1. Liability for Contents

As service providers, we are liable for own contents of these websites according to Sec. 7, paragraph 1 German Telemedia Act (TMG). However, according to Sec. 8 to 10 German Telemedia Act (TMG), service providers are not obligated to permanently monitor submitted or stored information or to search for evidences that indicate illegal activities.

Legal obligations to removing information or to blocking the use of information remain unchallenged. In this case, liability is only possible at the time of knowledge about a specific violation of law. Illegal contents will be removed immediately at the time we get knowledge of them.

2. Liability for Links

Our offer includes links to external third party websites. We have no influence on the contents of those websites, therefore we cannot guarantee for those contents. Providers or administrators of linked websites are always responsible for their own contents.

The linked websites had been checked for possible violations of law at the time of the establishment of the link. Illegal contents were not detected at the time of the linking. A permanent monitoring of the contents of linked websites cannot be imposed without reasonable indications that there has been a violation of law. Illegal links will be removed immediately at the time we get knowledge of them.

3. Copyright

Contents and compilations published on these websites by the providers are subject to German copyright laws. Reproduction, editing, distribution as well as the use of any kind outside the scope of the copyright law require a written permission of the author or originator. Downloads and copies of these websites are permitted for private use only.

The commercial use of our contents without permission of the originator is prohibited.

Copyright laws of third parties are respected as long as the contents on these websites do not originate from the provider. Contributions of third parties on this site are indicated as such. However, if you notice any violations of copyright law, please inform us. Such contents will be removed immediately.